### ISSUE TITLE
could i be whithe listed on the server

### ISSUE THREAD

**Issue by minecrafterseppe** [MrTubzy456/RequiemEvolution#2]
im loyal im wondering if i could be whithe listed on the server (minecrafterseppe)

**Comment by MrTubzy456** [comment]
You need to post an application on our website. Www.requiemforapickaxe.com

**Comment by Nagapito** [comment]
[http://www.requiemofapickaxe.com/](http://www.requiemofapickaxe.com/)

he misspelled the address
